### ISSUE TITLE
As a traffic engineer, I want to see the new AQ Data Collector developed by Datatellers (10 minutes) integrated in the ODH infrastructure

### ISSUE THREAD

**Issue by Piiit** [idm-suedtirol/bdp-commons#2]
Air Quality DC
@bertolla

**Comment by bertolla** [comment]
This can only can be done when the code is in the repository. Further more you need to differentiate between CI pipelines and testingpipelines:
- the CI pipeline is only meant for testing if the new code compiles and passes the tests(therefore tests must be written). Furthermore integration-tests can tell you if the code is still compatible with other components for example the writer
- testing pipelines also execute tests and additionally deploy the code to the testserver, but can only be created when the code is online

**Comment by rcavaliere** [comment]
It is correct to have it in testing, even if they have to implement corrections to the Data Collector

**Comment by bertolla** [comment]
Still wating ....

**Comment by rcavaliere** [comment]
Please also consider that in this sprint we would like to start testing the second Data Collector (open data APPA Trento).

**Comment by Piiit** [comment]
@rcavaliere @bertolla  Did PR #39 solve this issue?

**Comment by rcavaliere** [comment]
Since @bertolla has removed the "blocked" label, I guess yes. But I still have to check the data in the testing environment (will do it today).

**Comment by datatellers-devs** [comment]
Hopefully the data is consistent with the one we have in our database (we recreated it using [quickbuild.sh](https://github.com/idm-suedtirol/bdp-core/blob/master/quickbuild.sh)). It is to point out that we have been having issues with 1.2.4 having HttpClientErrorException - 404 null at [JSONPusher.java:69](https://github.com/idm-suedtirol/bdp-core/blob/master/dc-interface/src/main/java/it/bz/idm/bdp/json/JSONPusher.java#L69) that we're not having with the same datacollector code and the same [application.properties](https://github.com/idm-suedtirol/bdp-core/blob/master/dc-interface/src/main/resources/application.properties) but the previous versions of the dc-interface, even though the writer is currently running 1.2.4 flawlessly (and it seems compatible with dc-interface down to 1.0.2).

We figured it's most likely due to different environments. Hopefully it is not related to the old issue with data not appearing on your side.

**Comment by rcavaliere** [comment]
Checked the new DC version, everything works fine (including historical data retrieval). @Piiit or @bertolla can we go in production next week?

**Comment by rcavaliere** [comment]
@datatellers-devs we still have issues in the real-time data retrieval. Also @bertolla believes that there is some bug in the code that did not appear in the testing environment. Please fix this ASAP as we are here in the production environment already
![screenshot from 2019-01-18 07-50-57](https://user-images.githubusercontent.com/9825179/51370054-046c6380-1af6-11e9-98ce-c82ab3304d28.png)

**Comment by datatellers-devs** [comment]
@rcavaliere @bertolla the pull request is done and Jenkins is not complaining anymore! Sorry, had it failing because of a leftover reference and couldn't see it in the massive console output. The issues addressed and discussed should now be fixed, let us know how the testing phase goes.

The issue referred in the previous comment was due to the lack of getDateOfLastRecord in the first datacollector (which has now been added) mixed with the scarce reliability of the source API, which had rare data uploads. Not being able to get the last saved record forced us to rely on the API endpoint not using time intervals, since we did not have any possibility to set a starting date. This is now irrelevant to the datacollector which can correctly get the starting date, therefore collecting all the data.
